# Generated by Django 4.2.21 on 2025-06-02 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotApp', '0002_chathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='chatlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='chatlog',
            old_name='response',
            new_name='bot_response',
        ),
        migrations.RenameField(
            model_name='chatlog',
            old_name='user_query',
            new_name='user_message',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
