# Generated by Django 4.2.21 on 2025-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotApp', '0003_alter_chathistory_options_alter_chatlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
